name = "Terminal"
bundle_id = "org.mochios.terminal"
version = "0.1.0"
developer = "mochiOS"
entry = "entry.elf"
description = "Command-line terminal for mochiOS"
icon = "appicon.svg"

resources = [
    "appicon.svg",
]
