[workspace]

[package]
name = "terminal"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
viewkit = "1.0.1"

[target.'cfg(target_os = "mochios")'.dependencies]
libc = { git = "https://github.com/mochiOS/libc", package = "libc" }

[[bin]]
name = "terminal"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
