format = 1

[package]
provenance = "built-in"
id = "org.mochios.terminal"
name = "Terminal"
version = "0.1.0"
revision = 1
vendor = "mochiOS"
kind = "application"
architecture = "x86_64"
abi = "mochios-1"

[application]
entry = "entry.elf"
description = "Command-line terminal for mochiOS"
icon = "appicon.png"
resources = ["appicon.png"]

[[binary]]
path = "/system/applications/Terminal.app/entry.elf"
kind = "application"
requires = [
    "clipboard.read",
    "fs.read.all",
    "fs.write.tmp",
    "fs.write.user",
    "ipc.client",
    "ipc.server",
    "process.spawn",
    "window.create",
]
